# specify python as the language
language: python

# python versions to be used for testing
python:
   - "3.5"
 
install:
   - pip install -r requirements.txt

# test script

script:
   - python src/simple_validator.py spec/syngo_spec.yaml json/
